# Generated by Django 5.0.4 on 2024-12-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ImageAnnotation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="imageUrl",
        ),
        migrations.RemoveField(
            model_name="project",
            name="imageFolder",
        ),
        migrations.AddField(
            model_name="image",
            name="file",
            field=models.ImageField(default="images/default.png", upload_to="images/"),
        ),
    ]
