# Generated by Django 5.0.4 on 2024-12-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ImageAnnotation",
            "0002_remove_image_imageurl_remove_project_imagefolder_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="annotationFields",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
